### ISSUE TITLE
导航栏问题

### ISSUE THREAD

**Issue by 993681205** [weilanwl/coloruicss#105]
头部导航栏的高度不太对，导致右侧小一些
![image](https://user-images.githubusercontent.com/36142816/56269646-b67fef80-6126-11e9-9f01-71aaabdee602.png)

**Comment by jiangchuanqiang** [comment]
![Uploading image.png…]()

我也有这个问题

**Comment by 4cup** [comment]
建议仔细看看源代码，估计是CustomBar没值吧，看看代码就知道了

**Comment by weilanwl** [comment]
微信官方已知bug  https://developers.weixin.qq.com/community/develop/doc/000aa2ed070a681ca1583206a50800 等待微信官方修复吧
