### ISSUE TITLE
【BUG】checkbox 样式问题

### ISSUE THREAD

**Issue by sheng-di** [weilanwl/coloruicss#115]
![image](https://user-images.githubusercontent.com/13643746/56873587-eeabfa00-6a65-11e9-8ee8-00ffd771d8f4.png)
给`checkbox`只加了`round`属性
1、大小太小了，且无法调节
2、对号错位，而且错位不一致。

**Comment by supermebing** [comment]
radio {
      transform:scale(0.8);
    }

**Comment by rogerluo410** [comment]
![image](https://user-images.githubusercontent.com/5260711/62925802-b3032900-bde5-11e9-95fe-34e790370cfe.png)

checkbox .uni-checkbox-input {
  margin: 0;
  width: 24px;
  height: 24px;
}

to: 

checkbox .uni-checkbox-input {
  margin: 0;
  width: 36px;
  height: 36px;
}
