### ISSUE TITLE
请问modal框下面的原生组件，比如textarea会穿透modal，有没有办法

### ISSUE THREAD

**Issue by huanghaodong** [weilanwl/coloruicss#12]
请问modal框下面的原生组件，比如textarea会穿透modal，有没有办法

**Comment by weilanwl** [comment]
请详细查看 form表单组件 对应的textarea有做对应的设置

**Comment by huanghaodong** [comment]
![image](https://user-images.githubusercontent.com/24872469/49419699-fb803680-f7c2-11e8-844f-d14540e07afc.png)
modal框显示的时候，禁用textarea吗？

**Comment by weilanwl** [comment]
/pages/form/form textarea组件有相应的隐藏代码

**Comment by xujipm** [comment]
> /pages/form/form textarea组件有相应的隐藏代码

用了disabled后，在有输入的情况下是OK的，但是在 placeholder 状态下，placeholder的文字还是会在modal之上

**Comment by FirstJavaMaster** [comment]
> > /pages/form/form textarea组件有相应的隐藏代码
> 
> 用了disabled后，在有输入的情况下是OK的，但是在 placeholder 状态下，placeholder的文字还是会在modal之上

这种情况在微信开发者工具上不会出现, 实机模拟时就会出现. placeholder的文字处在modal之上
