### ISSUE TITLE
有没有文档，没有文档怎么开发

### ISSUE THREAD

**Issue by pbwei** [weilanwl/coloruicss#120]
每个 组件需要传什么参数
都不知道，怎么开发。
佩服各位3159star 怎么来的

**Comment by klren0312** [comment]
学习源码啊

**Comment by kingdle** [comment]
非常高效的样式，谢谢您的贡献

**Comment by tudoulei** [comment]
学习文件夹里的demo

**Comment by abrahamgreyson** [comment]
作者会说，他那种菜鸡不会写文档哈哈

**Comment by weilanwl** [comment]
我这种菜鸡不会写文档

**Comment by weilanwl** [comment]
这是个css库 你要啥直接复制就可以了 没有文档 封装的组件也只有一个 相应参数也在readme有写

**Comment by lonquan** [comment]
> 作者会说，他那种菜鸡不会写文档哈哈



> 作者会说，他那种菜鸡不会写文档哈哈

X_X 活捉一只大佬

**Comment by abrahamgreyson** [comment]
@lonquan  别闹 🤣

**Comment by zenghao0219** [comment]
这哪用的着文档

**Comment by qiuxiaojian** [comment]
还是需要完善文档的

**Comment by abrahamgreyson** [comment]
不用不用，哈哈哈哈哈哈哈哈



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: qiuxiaojian <notifications@github.com&gt;
发送时间: 2019年9月25日 16:30
收件人: weilanwl/ColorUI <ColorUI@noreply.github.com&gt;
抄送: 刘阳 <82011220@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[weilanwl/ColorUI] 有没有文档，没有文档怎么开发 (#120)




还是需要完善文档的
