### ISSUE TITLE
一运行就报错

### ISSUE THREAD

**Issue by zs1040466634** [weilanwl/coloruicss#125]
thirdScriptError
wx.getMenuButtonBoundingClientRect is not a function;at App onLaunch function;at api getSystemInfo success callback function
TypeError: wx.getMenuButtonBoundingClientRect is not a function

**Comment by YangZhengtian** [comment]
我也遇到了，不能使用自定义导航栏。

**Comment by zs1040466634** [comment]
因为基础库的版本太低了

**Comment by YangZhengtian** [comment]
那怎么解决啊？求助

**Comment by zs1040466634** [comment]
在官方微信小程序的开发工具上可以直接设置基础库的版本

**Comment by YangZhengtian** [comment]
啊 好了，感谢！

**Comment by zs1040466634** [comment]
没事

**Comment by aborn** [comment]
最底版本号：2.1.0
