### ISSUE TITLE
模态窗口顶部覆盖bug

### ISSUE THREAD

**Issue by Lingouzi** [weilanwl/coloruicss#129]
![IMG_FB8B6A16562D-1](https://user-images.githubusercontent.com/12908403/57498713-9996a080-730f-11e9-8ab7-f1436d386573.jpeg)
如图，顶部的普通窗口被遮盖。

**Comment by weilanwl** [comment]
看看版本库是不是最新的 没有调用到getMenuButtonBoundingClientRect [说明](https://developers.weixin.qq.com/miniprogram/dev/api/wx.getMenuButtonBoundingClientRect.html)

**Comment by tulongxCodes** [comment]
@weilanwl 我是扫描的readme中的小程序二维码看到的。刚才重试了一下，这块没毛病了。
不过又看到2个bug
1. 拓展-》向下拉动页面，顶部的NavBar会被遮盖
2. 拓展-》全局抽屉-》向下拉动页面，顶部的NavBar会上下抖动

**Comment by sky-like** [comment]
模态窗口顶部覆盖bug仍然存在，直接在微信查看“ColorUI”这个小程序就能看到，随便点击进入一个页面，顶部都有错位
