### ISSUE TITLE
发布到npm，发布到bootcdn

### ISSUE THREAD

**Issue by Akimotorakiyu** [weilanwl/coloruicss#143]
## 发布到npm

可以使用`npm i colorui`安装
可以使用`@import colorui`使用

## 发布到bootcdn

可以使用`<link rel="stylesheet" href="cdn.bootcss.com/colorui/version/index.css">`使用

### ColorUI用了都说好👏

**Comment by Nicholas003** [comment]
这样还是不能再vue项目中使用啊，知识一个包？？？  然并卵
