### ISSUE TITLE
港哥，有计划开发vue的版本吗？

### ISSUE THREAD

**Issue by Nicholas003** [weilanwl/coloruicss#148]
现在有nuiapp的版本照样不能再普通的项目上使用鸭。

**Comment by neozhu** [comment]
我认为还是专注微信小程序比较好，同时能提供更多的模版，比如类似电商的商品列表，或是社交类的card设计，照片墙这类设计。当然也可以做一个收费版本，针对不同的应用场景

**Comment by Nicholas003** [comment]
> 我认为还是专注微信小程序比较好，同时能提供更多的模版，比如类似电商的商品列表，或是社交类的卡片设计，照片墙这类设计。当然也可以做一个收费版本，针对不同的应用场景

如果专注小程序为什么还要开发nuiapp？  我看了uniapp打包的h5体验太差了~

**Comment by yz7805325** [comment]
自己改一下css就好了~ view替换成div,text换成span,亲测可用!!!
