### ISSUE TITLE
w哥，是我的误解么？为什么垂直导航的data的list你给的是空的数组？完全猜不出来应该是怎么写。

### ISSUE THREAD

**Issue by microkof** [weilanwl/coloruicss#150]
一开始尝试做了一个垂直导航的vue组件，然后发现不显示，我还傻乎乎的以为是样式不对，结果调了10分钟才发现。。。是因为list是空数据。

然而，我完全猜不出来官方演示小程序的list是怎么写的，所以好奇，为何作者的github的代码要故意清空list呢？

**Comment by weilanwl** [comment]
谁说我list空的 onLoad 有循环赋值啊

**Comment by microkof** [comment]
> 谁说我list空的 onLoad 有循环赋值啊

额是我学艺不精。但是，为什么把它封装成组件之后，onload的代码不执行？但是onReady的代码是执行的。

那么还是我什么地方搞错了么？

**Comment by Xavier9896** [comment]
> > 谁说我list空的 onLoad 有循环赋值啊
> 
> 额是我学艺不精。但是，还是有2大神奇之处：
> 
> 1. 为什么把它封装成组件之后，onload的代码不执行？但onReady的代码是执行的。那么还是我什么地方搞错了么？
> 2. 为什么
> 
> ```
> 						view.fields({
> 							size: true
> 						}, data => {
> ```
> 
> 这一块，data得到的值是null。

1.那就真的是你学艺不精了，去看看自定义组件的生命周期吧
2.代码不完整看不懂哪里有问题

**Comment by microkof** [comment]
> > > 谁说我list空的 onLoad 有循环赋值啊
> > 
> > 
> > 额是我学艺不精。但是，还是有2大神奇之处：
> > 
> > 1. 为什么把它封装成组件之后，onload的代码不执行？但onReady的代码是执行的。那么还是我什么地方搞错了么？
> > 2. 为什么
> > 
> > ```
> > 						view.fields({
> > 							size: true
> > 						}, data => {
> > ```
> > 
> > 
> > 这一块，data得到的值是null。
> 
> 1.那就真的是你学艺不精了，去看看自定义组件的生命周期吧
> 2.代码不完整看不懂哪里有问题

查清楚原因了，谢谢哥！

祝项目越来越好！

另外建议：下个版本尽量全flex化吧，比如list，那些width都是calc出来的，倒不如用flex。

**Comment by LIUHAI1231** [comment]
> > > > 谁说我list空的 onLoad 有循环赋值啊
> > > 
> > > 
> > > 额是我学艺不精。但是，还是有2大神奇之处：
> > > 
> > > 1. 为什么把它封装成组件之后，onload的代码不执行？但onReady的代码是执行的。那么还是我什么地方搞错了么？
> > > 2. 为什么
> > > 
> > > ```
> > > 						view.fields({
> > > 							size: true
> > > 						}, data => {
> > > ```
> > > 
> > > 
> > > 这一块，data得到的值是null。
> > 
> > 
> > 1.那就真的是你学艺不精了，去看看自定义组件的生命周期吧
> > 2.代码不完整看不懂哪里有问题
> 
> 查清楚原因了，谢谢哥！
> 
> 祝项目越来越好！
> 
> 另外建议：下个版本尽量全flex化吧，比如list，那些width都是calc出来的，倒不如用flex。

请问下  你是怎么解决的
原demo垂直导航组件是页面，我把它改成组件使用了
list在attached生命周期时创建，但滑动锚点时出问题
`VerticalMain(e) {
      let that = this;
      let list = this.data.list;
      let tabHeight = 0;
      if (this.data.load) {
        for (let i = 0; i < list.length; i++) {
          let view = wx.createSelectorQuery().select("#main-" + list[i].id);
          view.fields({
            size: true
          }, data => {            
            list[i].top = tabHeight;
            tabHeight = tabHeight + data.height;
            list[i].bottom = tabHeight;
          }).exec();
        }
      ...
`
这段代码中，能获取DOM，view有值，但是view.fields的回调方法中的参数data是null
请问这是咋回事？

**Comment by LIUHAI1231** [comment]
> > > > 谁说我list空的 onLoad 有循环赋值啊
> > > 
> > > 
> > > 额是我学艺不精。但是，还是有2大神奇之处：
> > > 
> > > 1. 为什么把它封装成组件之后，onload的代码不执行？但onReady的代码是执行的。那么还是我什么地方搞错了么？
> > > 2. 为什么
> > > 
> > > ```
> > > 						view.fields({
> > > 							size: true
> > > 						}, data => {
> > > ```
> > > 
> > > 
> > > 这一块，data得到的值是null。
> > 
> > 
> > 1.那就真的是你学艺不精了，去看看自定义组件的生命周期吧
> > 2.代码不完整看不懂哪里有问题
> 
> 查清楚原因了，谢谢哥！
> 
> 祝项目越来越好！
> 
> 另外建议：下个版本尽量全flex化吧，比如list，那些width都是calc出来的，倒不如用flex。

呃、代码格式不对  重发一个
`
VerticalMain(e) {

      let that = this;
      let list = this.data.list;
      let tabHeight = 0;
      if (this.data.load) {
        for (let i = 0; i < list.length; i++) {
          let view = wx.createSelectorQuery().select("#main-" + list[i].id);
          view.fields({
            size: true
          }, data => {            
            list[i].top = tabHeight;
            tabHeight = tabHeight + data.height;
            list[i].bottom = tabHeight;
          }).exec();
        }
        that.setData({
          load: false,
          list: list
        })
      }
  ...
}
`
