### ISSUE TITLE
cu-custom作为小程序头部在IOS下会被拉动；且偶尔会整体偏移向上

### ISSUE THREAD

**Issue by 94do** [weilanwl/coloruicss#160]
cu-custom作为小程序头部在IOS下会被拉动；且偶尔会整体偏移向上，目测是因为padding的部分被偏移出屏幕导致的，且下拉不会回来。

**Comment by zhangfengsheng1** [comment]
同问   是否已解决？

**Comment by squarezhou** [comment]
这是小程序API wx.getMenuButtonBoundingClientRect在iOS下的BUG，可以在app.js设置CustomBar时手动判断兼容一下

**Comment by shirne** [comment]
原生小程序的下拉刷新效果会连自定义状态栏一起下拉，所有系统都这样吧。
这个问题，，应该只能等微信更新解决。
我目前是禁用下拉刷新，然后自己在scroll-view上模拟了一个

**Comment by dengqianggh** [comment]
你是？



---原始邮件---
发件人: "shirne"<notifications@github.com&gt;
发送时间: 2019年9月5日(星期四) 下午3:12
收件人: "weilanwl/ColorUI"<ColorUI@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [weilanwl/ColorUI] cu-custom作为小程序头部在IOS下会被拉动；且偶尔会整体偏移向上 (#160)



原生小程序的下拉刷新效果会连自定义状态栏一起下拉，所有系统都这样吧。
 这个问题，，应该只能等微信更新解决。
 我目前是禁用下拉刷新，然后自己在scroll-view上模拟了一个
