### ISSUE TITLE
底部自定义tabbar onLoad无法加载数据

### ISSUE THREAD

**Issue by pygroos** [weilanwl/coloruicss#173]

**Comment by vcan** [comment]
遇到同样的问题，如果设置index页面为首页，其他页面的onload无法加载，请问你解决了吗

**Comment by pygroos** [comment]
> 遇到同样的问题，如果设置index页面为首页，其他页面的onload无法加载，请问你解决了吗

没解决，改换原生tabbar了。

**Comment by vcan** [comment]
谢谢，后来我也换原生了。找了半天没发现哪个地方写的有问题。希望作者尽快的出文档吧。

**Comment by gameruleCEO** [comment]
我今天这个问题搞了好久。怎么试都不行，这是让我放弃用原生的节奏啊😱

**Comment by archosaur** [comment]
不打算解决了吗？

**Comment by gameruleCEO** [comment]
planA：可以绑定底部切换事件充当onload，所有的数据初始化均放到此绑定事件上
planB：换原生|mounted
有问题私我，hhhh

**Comment by mobaixin** [comment]
一个很傻的办法，数据在app.js里面加载，然后放在缓存中，切换页面后直接从缓存中取数据，实测可行，唉，被逼无奈
