### ISSUE TITLE
列表左滑速度过慢

### ISSUE THREAD

**Issue by DonkeXu** [weilanwl/coloruicss#175]
列表中，左滑列表，用着感受有点奇怪，敏感性可以自己通过js改一下，但是速度啥的很奇怪。
建议优化一下

**Comment by peihuanhuan** [comment]
左滑速度的确很慢

**Comment by peihuanhuan** [comment]
有什么参数能调整滑动速度或者敏感性吗？

**Comment by dengqianggh** [comment]
你好，你知道怎么弄那个留言回复吗？还有就是模板消息提醒。能跟我分享一下吗？




------------------ 原始邮件 ------------------
发件人: "tangtang"<notifications@github.com>;
发送时间: 2019年9月13日(星期五) 下午4:47
收件人: "weilanwl/ColorUI"<ColorUI@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [weilanwl/ColorUI] 列表左滑速度过慢 (#175)




有什么参数能调整滑动速度或者敏感性吗？

**Comment by peihuanhuan** [comment]
这是因为你开了订阅吧

![image](https://user-images.githubusercontent.com/27762147/64849945-0e277600-d647-11e9-8108-0915b91cd0f0.png)

**Comment by dengqianggh** [comment]
你好，你是？



------------------ 原始邮件 ------------------
发件人: "tangtang"<notifications@github.com>;
发送时间: 2019年9月13日(星期五) 下午4:54
收件人: "weilanwl/ColorUI"<ColorUI@noreply.github.com>;
抄送: "2532310513"<2532310513@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [weilanwl/ColorUI] 列表左滑速度过慢 (#175)




这是因为你开了订阅吧

**Comment by TLingC** [comment]
@peihuanhuan 调整敏感性
https://github.com/weilanwl/ColorUI/issues/152#issuecomment-506172911

**Comment by TLingC** [comment]
滑动速度是改css里的transition

**Comment by gujiwuqing** [comment]
大佬们。为什么我左滑写不了那个删除事件呢，求告知如何解决

**Comment by TLingC** [comment]
你的代码怎么写的？



---原始邮件---
发件人: "孤寂无情"<notifications@github.com&gt;
发送时间: 2020年1月4日(周六) 晚上6:22
收件人: "weilanwl/ColorUI"<ColorUI@noreply.github.com&gt;;
抄送: "TLingC"<my@tlingc.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [weilanwl/ColorUI] 列表左滑速度过慢 (#175)



大佬们。为什么我左滑写不了那个删除事件呢，求告知如何解决
