### ISSUE TITLE
发现一个小bug，垂直导航

### ISSUE THREAD

**Issue by typ1758** [weilanwl/coloruicss#182]
点击到最后一个，在切换的到倒数第二个，来回切换的时候，点击到最后一个会跳到第二个

**Comment by typ1758** [comment]
为什么会写
 let scrollTop = e.detail.scrollTop + 20;
        for (let i = 0; i < list.length; i++) {
            if (scrollTop > list[i].top && scrollTop < list[i].bottom) {
                that.setData({
                    VerticalNavTop: (list[i].id - 1) * 50,
                    TabCur: list[i].id
                })
                console.log(this.data.TabCur,123)
                return false
            }
        }
这里在去设置TabCur？

**Comment by MSamor** [comment]
这个问题你怎么解决的，我今天也发现了。
