### ISSUE TITLE
light颜色小Bug

### ISSUE THREAD

**Issue by Fog3211** [weilanwl/coloruicss#184]
版本： ColorUi for uniApp  v2.1.6
问题描述： 使用镂空的绿色，黄色在真机上会展示成字体颜色与背景色相同  

期望表现：  
![avatar](https://img.fog3211.com/JO23%7BDMJXZFA85_%7BW04%60%7DRX.png)
真机表现：（PC端正常）  
![avatar](https://img.fog3211.com/%25MY%25B%5D%7DM%5D9WV59ROSB9%25_HS.png)

Bug：（uni-app中 ColorUI/Colorui-UniApp/colorui/main.css 黄色绿色十六进制代码多了两位）  

![avatar](https://img.fog3211.com/53%7BJ_L1MT4ARY%7DN14~GRP%5DB.png)

**Comment by wulongqiu** [comment]
今天也发现这个背景色 Bug
