### ISSUE TITLE
请求加入 colorUI 的 iconfont 协作

### ISSUE THREAD

**Issue by excing** [weilanwl/coloruicss#185]
感谢作者的奉献，ColorUI 的 Icon 库中，有不少项目中会用到 Icon 没有，因此请求加入 Icon 的更新中来。

我看了下 ColorUI 用的是 iconfont 的字体库， iconfont 项目允许其他成员参与一起维护，希望作者可以考虑一下，谢谢。

**Comment by szylmzs** [comment]
支持

**Comment by GSZS** [comment]
支持

**Comment by sunyitao** [comment]
同求，或者把下载至本地的zip文件发出来也行
