### ISSUE TITLE
关于： https://image.weilanwl.com/gif/wave.gif 报错

### ISSUE THREAD

**Issue by aTong9** [weilanwl/coloruicss#197]

**Comment by lizhongzhen11** [comment]
403禁用吧，我之前也发现了，估计很多人都在直接用作者的线上图，这样会增加他服务器流量使用吧，所以他可能对请求域名做了限制，建议你从官方demo里面考到自己项目里，用本地的。

**Comment by aTong9** [comment]
> 403禁用吧，我之前也发现了，估计很多人都在直接用作者的线上图，这样会增加他服务器流量使用吧，所以他可能对请求域名做了限制，建议你从官方demo里面考到自己项目里，用本地的。

好的，谢谢🙏
