### ISSUE TITLE
[建议]工具类样式，是否加个 !important合理一些

### ISSUE THREAD

**Issue by shirne** [weilanwl/coloruicss#199]
尝试用您的UI做一个商城小程序，发现工具类 （颜色 ，字体，等这种一个类只针对一条样式的类） 的样式会被自己写的覆盖掉， 是否在这些类定义的样式加上!important更合理一些。

感谢开源！

**Comment by d1y** [comment]
> 尝试用您的 UI 做一个商城小程序，发现工具类 （颜色 ，字体，等这种一个类只针对一条样式的类） 的样式会被自己写的覆盖掉， 是否在这些类定义的样式加上！important 更合理一些。
> 
> 感谢开源！

我记得貌似在上上几个版本前是有`!important`的, 现在貌似没有了
（某些场景下使用`!important`并不合理, 参考: [CSDN](https://www.cnblogs.com/shinnyChen/p/3758166.html))

**Comment by dayudada** [comment]
自己手工改一下colorui下的main.csss

**Comment by shirne** [comment]
> 我记得貌似在上上几个版本前是有`!important`的, 现在貌似没有了
> （某些场景下使用`!important`并不合理, 参考: [CSDN](https://www.cnblogs.com/shinnyChen/p/3758166.html))

看了，我说的是针对单条规则的样式，比如一个字号，一个颜色对应的一个css类，加了这个类，肯定就是要这个样式，不要这个样式把类名去掉也不影响别的。
而自定义的一些模块的样式里一旦设了一个默认的样式或字体，css path一般是多重的，必定就覆盖掉了特定的样式，所以我觉得，针对单条规则的样式，加上更合理些。
而且大多数前端框架，也是这样实践的
