### ISSUE TITLE
iphone7 微信小程序状态栏高度不对

### ISSUE THREAD

**Issue by JokerLoLgrey** [weilanwl/coloruicss#205]
iphone7 微信小程序状态栏高度显示不对
![b2472b93f9272a9a0182e1af71acdb3](https://user-images.githubusercontent.com/33446705/64948524-dc621980-d8a9-11e9-9ff2-f745a133395c.jpg)

**Comment by hxinyu0591** [comment]
不定时碰到此问题，求解！

**Comment by haozes** [comment]
同样问题

**Comment by shirne** [comment]
这个是微信接口不稳定的bug，可以预先写好这个参数，调用失败或返回数据不对的时候使用预设的参数显示。可以参考我做的小程序商城源码
[小程序商城](https://github.com/shirne/shop_mapp/blob/master/app.js)
