### ISSUE TITLE
导航顶部偶尔不显示，是什么问题？

### ISSUE THREAD

**Issue by renbaolin** [weilanwl/coloruicss#212]
遇到好几次不显示的情况。
![image](https://user-images.githubusercontent.com/10153944/65422664-ba344280-de39-11e9-8ca0-d501a4271127.png)

**Comment by aqHi** [comment]
遇到同样的问题

**Comment by panghao0518** [comment]
同问

**Comment by srauni** [comment]
我这也是，前天信心满满发给女神，结果她打开就没有顶栏，十分尴尬

**Comment by haozes** [comment]
新代码好像已经加入此解决方案，但并未解决

**Comment by jonahzheng** [comment]
android 和ios都出现这个情况

**Comment by createskyak** [comment]
什么问题呢？更新了版本后还是不行。

**Comment by InsHomePgup** [comment]
用别的导航栏吧，插件市场里有

createskyak <notifications@github.com> 于2019年10月24日周四 下午3:23写道：

**Comment by AAADream** [comment]
这个问题解决了吗

**Comment by AAADream** [comment]
> 遇到同样的问题



> 遇到好几次不显示的情况。
> ![image](https://user-images.githubusercontent.com/10153944/65422664-ba344280-de39-11e9-8ca0-d501a4271127.png)

你好问题解决了吗

**Comment by Nicholas003** [comment]
在头部组件中加入以下代码即可解决
`created() {
			// console.log(1)
			uni.getSystemInfo({
				success: (e) => {
					// #ifndef MP
					this.StatusBar = e.statusBarHeight;
					if (e.platform == 'android') {
						// #ifndef MP
						this.CustomBar = e.statusBarHeight + 50;
						// #endif
						// #ifdef H5
						this.CustomBar = e.statusBarHeight + 45;
						// #endif
					} else {
						this.CustomBar = e.statusBarHeight + 45;
					};
					// #endif

					// #ifdef MP-WEIXIN
					this.StatusBar = e.statusBarHeight;
					let custom = wx.getMenuButtonBoundingClientRect();
					this.Custom = custom;
					this.CustomBar = custom.bottom + custom.top - e.statusBarHeight;
					// #endif		

					// #ifdef MP-ALIPAY
					this.StatusBar = e.statusBarHeight;
					this.CustomBar = e.statusBarHeight + e.titleBarHeight;
					// #endif
				}
			})
		},`
问题的原因是刚一打开的时候有可能设备高度信息还没获取到，就初始化完成了，把初始化的代码方才组件的created即可解决
