### ISSUE TITLE
页面刷新后，返回按扭失效

### ISSUE THREAD

**Issue by bln7** [weilanwl/coloruicss#227]
如题，点击返回按扭时，只是刷新当前页。

**Comment by InsHomePgup** [comment]
试试插件市场里其他的自定义导航栏，好用的很

bln7 <notifications@github.com> 于2019年10月23日周三 上午10:29写道：

**Comment by huangguorui** [comment]
![image](https://user-images.githubusercontent.com/29142466/71434860-5879c200-2721-11ea-9f12-9113ae5d549e.png)
导航栏为什么会出现点不动的情况，就是不可以返回上一页
