### ISSUE TITLE
getSystemInfo 异步的  万一界面渲染时  CustomBar还没计算出来怎么办

### ISSUE THREAD

**Issue by Blizzard-liu** [weilanwl/coloruicss#229]
wx.getSystemInfo({
      success: e => {
        this.globalData.StatusBar = e.statusBarHeight;
        let capsule = wx.getMenuButtonBoundingClientRect();
		if (capsule) {
		 	this.globalData.Custom = capsule;
			this.globalData.CustomBar = capsule.bottom + capsule.top - e.statusBarHeight;
		} else {
			this.globalData.CustomBar = e.statusBarHeight + 50;
		}
      }
    })

**Comment by zengzhanliang** [comment]
getSystemInfo 改成同步方法就行了，具体看文档：https://developers.weixin.qq.com/miniprogram/dev/api/base/system/system-info/wx.getSystemInfoSync.html

**Comment by HuYueling** [comment]
你好！你的问题解决了么，我现在测试的时候真机和调试都没问题，但是发布体验版后，就说StatusBar undefined,请教一下，这是什么问题
