### ISSUE TITLE
iOS上还是有错位的问题，系统版本号13.0的

### ISSUE THREAD

**Issue by canyu9512** [weilanwl/coloruicss#232]
看了下上次的更新，只是app.js里面添加了判断吗，前段时间更新了，今天iOS上还是遇到了错位的问题

**Comment by name-cq** [comment]
兄弟解决了么

**Comment by canyu9512** [comment]
> 兄弟解决了么

没有，我设置了个默认高度还是一样。。。而且还很频繁，蛋疼

**Comment by name-cq** [comment]
> > 兄弟解决了么
> 
> 没有，我设置了个最小高度还是一样。。。而且还很连续，蛋疼

好吧~~~~

**Comment by canyu9512** [comment]
> > > 兄弟解决了么
> > 
> > 
> > 没有，我设置了个最小高度还是一样。。。而且还很连续，蛋疼
> 
> 好吧~~~~

我是感觉是获取设备信息没有获取到或者获取比较慢，导致加载的时候高度有问题，但是设置了默认的高度，还是有问题

**Comment by 251205668** [comment]
解决办法还是有的 要改一点custom.vue
