### ISSUE TITLE
IOS微信小程序 顶部状态栏错位

### ISSUE THREAD

**Issue by BuTingBa** [weilanwl/coloruicss#234]
我已经更新了最新的代码，但是还是会错位，基本上都发生在iOS系统上。
主要表现是，会将内容上移，我的搜索栏、菜单操作栏都会不见，有些时候还会出现鬼畜一般的抖动。
求求各位大佬救救孩子吧！我真的是太难了。在不解决好，我就要炒鱿鱼了！

**Comment by j2ee-haydon** [comment]
哎，我的也是，建议别用自定义custom了吧

**Comment by name-cq** [comment]
解决了么！！我也有这个问题

**Comment by BuTingBa** [comment]
好像是因为微信小程序的定位问题，偶尔会获取不到位置。可以参见小程序文档。
我没有解决，我用了其他补救的方法

**Comment by name-cq** [comment]
> 好像是因为微信小程序的定位问题，偶尔会获取不到位置。可以看到小程序文档。
> 我没有解决，我用了其他替代的方法

好吧谢谢

**Comment by pygroos** [comment]
> 好像是因为微信小程序的定位问题，偶尔会获取不到位置。可以参见小程序文档。
> 我没有解决，我用了其他补救的方法

请教用了什么补救的方法

**Comment by QJune** [comment]
> 我已经更新了最新的代码，但是还是会错位，基本上都发生在iOS系统上。
> 主要表现是，会将内容上移，我的搜索栏、菜单操作栏都会不见，有些时候还会出现鬼畜一般的抖动。
> 求求各位大佬救救孩子吧！我真的是太难了。在不解决好，我就要炒鱿鱼

> 好像是因为微信小程序的定位问题，偶尔会获取不到位置。可以参见小程序文档。
> 我没有解决，我用了其他补救的方法

如果是偶尔获取不到，你可能用了异步获取系统信息，你换为同步那个api
