### ISSUE TITLE
picker多列选择时，改变其中一列，其他列不会实时更新

### ISSUE THREAD

**Issue by as299999** [weilanwl/coloruicss#240]
要使用深度拷贝才可以
let data = {
	multiArray: JSON.parse(JSON.stringify(this.multiArray)),
	multiIndex: JSON.parse(JSON.stringify(this.multiIndex))
};
还有建议开发个pirck-view的组件，因为pirck样式改变不了，选项太长时会显示省略号，但是屏幕还有很多宽度

**Comment by WeiYuanStudio** [comment]
HBuilderX版本：2.6.5.20200314

使用uni开发微信小程序，同遇到这个问题。

而且官方demo也未能刷新多列
以官方demo为例，解决方案：
在<https://github.com/weilanwl/ColorUI/blob/master/Colorui-UniApp/pages/component/form.vue#L326>前加入下列两行代码成功解决这个问题。

```js
this.multiArray = null;
this.multiIndex = null;
```
