### ISSUE TITLE
请问各种claaName代表的样式那里又文档说明？

### ISSUE THREAD

**Issue by syymo** [weilanwl/coloruicss#242]
想用各种效果 但是不知道怎么加上去

**Comment by d1y** [comment]
> 想用各种效果 但是不知道怎么加上去

没有文档,  `css` 不好写文档, `demo` 既文档, 你可以把 `/demo` 运行在小程序, 找到你需要的需要的样式 `class`, 自行复制即可, 祝玩的开心哈

![image](https://user-images.githubusercontent.com/45585937/69627563-d6e13680-1085-11ea-88fc-7a166dc8715a.png)

**Comment by cndew** [comment]
demo里面有详细的代码 可以参看使用

**Comment by lixiaoming-bit** [comment]
哇，没有一个规范可以看么，全靠删减class去找顶不住啊

**Comment by Greenplumwine** [comment]
建议自己照源码看一下
