### ISSUE TITLE
没有文档嘛

### ISSUE THREAD

**Issue by geekchenzx** [weilanwl/coloruicss#247]

**Comment by xzeu** [comment]
http://docs.xzeu.com

**Comment by chenzx023** [comment]
> 先写了一部份，大家先对付看着，另外如果有一块维护的可以邮件我，
> 现在的文档地址：http://docs.xzeu.com

好的有文档就行

**Comment by syxchina** [comment]
方便查阅版本 https://www.yuque.com/swing-xcgis/hytn5l

**Comment by xzeu** [comment]
> 
> 
> 方便查阅版本 https://www.yuque.com/swing-xcgis/hytn5l

大家转到这里吧
