### ISSUE TITLE
demo使用

### ISSUE THREAD

**Issue by fatnij** [weilanwl/coloruicss#250]
![1576131125191](https://user-images.githubusercontent.com/58071874/70687760-02515b80-1ceb-11ea-9e32-310b36ea0ce1.jpg)
验证码按钮小写问题，款状按钮不能全屏

**Comment by fatnij** [comment]
<cu-custom bgColor="bg-gradual-blue" isBack="{{true}}">
  <view slot="content">新用户注册</view>
</cu-custom>
<form>
  <view class="cu-form-group margin-top">
    <view class="title">手机号码</view>
    <input placeholder="请输入手机号码"></input>
    <view class="cu-capsule radius">
      <view class="cu-tag bg-blue">
        +86
      </view>
      <view class="cu-tag line-blue">
        中国大陆
      </view>
    </view>
  </view>
  <view class="cu-form-group">
    <view class="title">验证码</view>
    <input placeholder="请输入验证码"></input>
    <button class="cu-btn bg-cyan shadow">验证码</button>
  </view> 
</form>

<view class="cu-bar margin-top bg-white">
  <view class="action">
    <text class="cuIcon-title text-blue"></text>块状按钮
  </view>
</view>
<view class="padding flex flex-direction">
  <button class="cu-btn bg-grey lg">玄灰</button>
  <button class="cu-btn bg-red margin-tb-sm lg">嫣红</button>
</view>

**Comment by fatnij** [comment]
`
<cu-custom bgColor="bg-gradual-blue" isBack="{{true}}">
  <view slot="content">新用户注册</view>
</cu-custom>
<form>
  <view class="cu-form-group margin-top">
    <view class="title">手机号码</view>
    <input placeholder="请输入手机号码"></input>
    <view class="cu-capsule radius">
      <view class="cu-tag bg-blue">
        +86
      </view>
      <view class="cu-tag line-blue">
        中国大陆
      </view>
    </view>
  </view>
  <view class="cu-form-group">
    <view class="title">验证码</view>
    <input placeholder="请输入验证码"></input>
    <button class="cu-btn bg-cyan shadow">验证码</button>
  </view> 
</form>

<view class="cu-bar margin-top bg-white">
  <view class="action">
    <text class="cuIcon-title text-blue"></text>块状按钮
  </view>
</view>
<view class="padding flex flex-direction">
  <button class="cu-btn bg-grey lg">玄灰</button>
  <button class="cu-btn bg-red margin-tb-sm lg">嫣红</button>
</view>
`

**Comment by Greenplumwine** [comment]
将cu-btn这个类去掉，然后自己调整即可

**Comment by sinhang** [comment]
app.json里面的 "style": "v2", 去掉就行了。
