### ISSUE TITLE
[建议]提供一份全面的开发文档

### ISSUE THREAD

**Issue by henan715** [weilanwl/coloruicss#258]
git主您好，您的组件非常好用，不过对于新手而言上手还是有点麻烦，能否提供一份较为全面的开发文档？

**Comment by Greenplumwine** [comment]
建议学习的办法：
这个ui组件库，其实就是能用上的css样式库
如果你想是使用这个库，先进入colorUI小程序，找到你想用的样式
然后去找一下源码，放在你自己的代码里。然后在修改修改即可

**Comment by chunbobo** [comment]
> 建议学习的办法：
> 这个ui组件库，其实就是能用上的css样式库
> 如果你想是使用这个库，先进入colorUI小程序，找到你想用的样式
> 然后去找一下源码，放在你自己的代码里。然后在修改修改即可

还是迫切希望有个文档....这么漂亮的UI，没个文档好难受

**Comment by Ichabood** [comment]
什么时候可以出个文档啊

**Comment by zizxzy** [comment]
> 什么时候可以出个文档啊

http://docs.xzeu.com/#/

**Comment by LancCJ** [comment]
这还用文档，直接找到界面复制就行了。。。
