### ISSUE TITLE
app.json中如果设置了 style:"v2"，部分组件出现问题

### ISSUE THREAD

**Issue by herowind** [weilanwl/coloruicss#260]
button icon radio checkbox switch slider这些组件可能受到影响
在扩展组件中的 search-form “搜索”按钮大小异常

**Comment by xyly624** [comment]
我也遇到这个问题了。ColorUI v2.1.4
`<view class="cu-bar search bg-white">
    <view class="search-form round">
      <text class="cuIcon-search"></text>
      <input type="text" placeholder="搜索图片、文章、视频" confirm-type="search"></input>
    </view>
    <view class="action">
      <button class="cu-btn bg-green shadow-blur round">搜索</button>
    </view>
  </view>`

设置了 style:"v2" :
![image](https://user-images.githubusercontent.com/1833280/74651096-0d7aa900-51be-11ea-98d0-78e5512c2286.png)
去掉 style 配置后:
![image](https://user-images.githubusercontent.com/1833280/74651140-271bf080-51be-11ea-8813-af95ebb71511.png)

**Comment by jsuper1980** [comment]
同样的问题

**Comment by aylcf** [comment]
同样的问题，加上style:"v2"后，问题如上图。试了一下，去掉这句就可以了。如果不去掉，就要把调试基础库版本降下来。2.8.0以下基础库版本都可以。
