### ISSUE TITLE
分享一个从ColorUi生成不同颜色主题的工具.

### ISSUE THREAD

**Issue by zero0-1one** [weilanwl/coloruicss#274]
将ColorUi中不颜色映射成多组主题.
轻松的为ColorUi增加或替换颜色规则.
按模块导出的main-lite.css,减少 css 文件大小

[https://github.com/zero0-1one/colorui-theme](https://github.com/zero0-1one/colorui-theme)

**Comment by MakerGYT** [comment]
小程序拾色器（颜色选择器）组件[mini-color-picker](https://github.com/MakerGYT/mini-color-picker),通过调色盘取色，用于用户自定义场景。
![预览](https://imgkr.cn-bj.ufileos.com/f04ae7f1-8a28-4761-acb4-db25616f55b2.png)
