### ISSUE TITLE
uni.showToast被cu-modal挡住了

### ISSUE THREAD

**Issue by heshule** [weilanwl/coloruicss#277]
如题，不知道有没有其他同学也同样遇到的。在显示了cu-modal  bottom-modal的情况下，如果uni.showToast，这个toast会显示在modal层下面，有同学知道怎么改吗，尝试改过z-index，但是没有用

**Comment by crstudio** [comment]
我也遇到了，不知所措啊。

**Comment by crstudio** [comment]
修改 modal 的z-index， 因为modal默认的z-inde是1110，儿toast的z-index才999。
