### ISSUE TITLE
图标名称与图标错位

### ISSUE THREAD

**Issue by Mrokor** [weilanwl/coloruicss#29]
图标名称与图标错位；
是否共享图标库(www.iconfont.cn)

**Comment by weilanwl** [comment]
图标基本使用的是官方淘宝的库，具体你可以看下[https://www.iconfont.cn/collections/detail?spm=a313x.7781069.1998910419.d9df05512&cid=33](https://www.iconfont.cn/collections/detail?spm=a313x.7781069.1998910419.d9df05512&cid=33)

**Comment by i5920** [comment]
谢谢,不知道为什么用这些图标往后老是图标与名称不对应。。。现在有这个来源我页可以选择性的使用了。

**Comment by weilanwl** [comment]
具体可以看下根目录下的icon.wxss文件是否和对应版本的demo一样
