### ISSUE TITLE
微信小程序真机调试的时候发现steps组件步骤框的链接线错位

### ISSUE THREAD

**Issue by gao-junfeng** [weilanwl/coloruicss#290]
在虚拟机上是正常的 在真机调试中发现这线段是有偏移的  我拖动ColorUI/demo/这个路径进的微信小程序进行调试的

**Comment by Bill66888** [comment]
我也是，但是之前没有，最近发生的问题！

**Comment by Bill66888** [comment]
解决了！方法如下：
main.wxss 2722
原来：left: calc(0px - (100% - 80rpx) / 2);
改成：left: calc(0rpx - (100% - 80rpx) / 2);

**Comment by gao-junfeng** [comment]
是css rpx/px的问题 兄弟你真棒 楼上正解

**Comment by ArtyomGuiyuan** [comment]
谢谢三楼的大兄弟 解决了

**Comment by 235832289** [comment]
谢谢三楼的大兄弟 解决了

**Comment by RogerLiNing** [comment]
> 解决了！方法如下：
> main.wxss 2722
> 原来：left: calc(0px - (100% - 80rpx) / 2);
> 改成：left: calc(0rpx - (100% - 80rpx) / 2);

感谢三楼的兄弟，更改colorui目录下的main.css的`2695`行更为方便，这样就不需要每次都要更改微信小程序的css了：
```css
left: calc(0px - (100% - 80upx) / 2);
```
改为
```css
left: calc(0upx - (100% - 80upx) / 2);
```

**Comment by lubianfuchen** [comment]
这个没人提交一下吗

**Comment by C4az6** [comment]
@RogerLiNing thank you very very much!
