### ISSUE TITLE
希望再多出一些组件，还是有点少

### ISSUE THREAD

**Issue by mcwenzai** [weilanwl/coloruicss#292]

**Comment by MakerGYT** [comment]
小程序拾色器（颜色选择器）组件[mini-color-picker](https://github.com/MakerGYT/mini-color-picker),通过调色盘取色，用于用户自定义场景。
![预览](https://imgkr.cn-bj.ufileos.com/f04ae7f1-8a28-4761-acb4-db25616f55b2.png)

**Comment by iamzaizai** [comment]
colorui本就不是组件，只是纯css，由用户自行搭配class，进行布局，纯css，更自由，但对于css不熟的，可能上手毕竟难。不过，不要担心，新版本采用组件化的模式，就快要发布了，耐心等待哦。
