### ISSUE TITLE
求更新啊

### ISSUE THREAD

**Issue by tigerleeli** [weilanwl/coloruicss#293]
首先感谢开源做出这么好的UI，但是目前这个用于V3有些样式有问题，希望可以继续更新，再次感谢！希望可以召回更新

**Comment by iamzaizai** [comment]
新版本已经开发很久了，就快要见面了，新版本几乎重构，采用了组件化的模式

**Comment by tigerleeli** [comment]
> 新版本已经开发很久了，就快要见面了，新版本几乎重构，采用了组件化的模式

好的 期待~
