### ISSUE TITLE
建议增加更多的图标。找图标有些费劲，分类后会更好

### ISSUE THREAD

**Issue by wenchuan2** [weilanwl/coloruicss#306]
现在找图标有点费劲，建议可以参考下Vant Weapp的设计
https://youzan.github.io/vant-weapp/#/intro

**Comment by iamzaizai** [comment]
colorui目前用的图标库是：[https://www.iconfont.cn/collections/detail?spm=a313x.7781069.1998910419.d9df05512&cid=33](iconfont，手机淘宝图标库)，图标不是每个人项目，每个图标都会用到，每个项目的业务也不一样，所用到的也不一样，官方能提供的，也只能是基础图标库，如果考虑更多业务的话，那不得上万个图标才能满足？那对开发者来说，找起来，也是一样麻烦，对一些小项目来说，根本用不到那么多图标，也会很鸡肋。所以，图标库的，有需求，可以自行按照各平台的要求，引入新的图标库即可。
