### ISSUE TITLE
单页面下拉刷新能生效吗？

### ISSUE THREAD

**Issue by BiggerWu** [weilanwl/coloruicss#308]
我试了下，不用colorui的时候，下拉刷新是没问题的，我项目使用了colorui然后下拉刷新不触发，请问是colorui的问题吗？

**Comment by InsHomePgup** [comment]
和pages.json里面的页面配置有关，引入一个css库和下拉刷新会有什么冲突？？？？？？？

**Comment by iamzaizai** [comment]
colorui只是纯css，理论上是不影响的，建议仔细排查下问题，检查冲突问题。
