### ISSUE TITLE
colorui自定议顶部导航的背景色不生效

### ISSUE THREAD

**Issue by dingchenghong** [weilanwl/coloruicss#309]
`<cu-custom bgColor="bg-my-green">
    <view slot="content">
      <image src="/images/cjkz.png" mode="widthFix"></image>
    </view>
</cu-custom>`

bg-my-green，是我自定义的颜色，但是不生效，大家有遇到过这种情况吗？
bg-my-green样式已经加到main.wxss文件里了

![color-ui](https://user-images.githubusercontent.com/4938801/89498668-41d83500-d7f1-11ea-96e8-b7b51cb3ff9b.png)

**Comment by iamzaizai** [comment]
可以尝试修改cu-custom这个组件文件里的样式看看。
