### ISSUE TITLE
ColorUI表单验证, 输入非空提示要怎么支持?

### ISSUE THREAD

**Issue by gclsoft** [weilanwl/coloruicss#310]
![image](https://user-images.githubusercontent.com/1269898/89735204-6a7f5980-da93-11ea-802e-08dba6ecbfb8.png)

**Comment by chunchunc** [comment]
自己写js判断

**Comment by iamzaizai** [comment]
colorui非组件，只是纯css，组件还是官方的组件，需要自行编写逻辑代码处理
