### ISSUE TITLE
可以公布icon图标库的地址嘛！不是ali cdn 地址！

### ISSUE THREAD

**Issue by codedart2018** [weilanwl/coloruicss#312]
图标挺全的。但大部份用不上，为了节约空间资源，希望公布下图标地址。我们可以按需要自己打包适合自己的图标！

**Comment by marren06** [comment]
![image](https://user-images.githubusercontent.com/17778482/93434959-5c76f100-f8fb-11ea-811c-c649f54fccf1.png)
这图标到底是什么？ 也不知道  

一楼的小姐姐说的对，求图标地址！

谢谢！

**Comment by sunyitao** [comment]
同样有自定义图标的需求，就是把https://www.iconfont.cn/中项目地址公布出来，或者在icon项目管理中下载至本地，然后把zip文件发布出来就行。

**Comment by iamzaizai** [comment]
> ![image](https://user-images.githubusercontent.com/17778482/93434959-5c76f100-f8fb-11ea-811c-c649f54fccf1.png)
> 这图标到底是什么？ 也不知道
> 
> 一楼的小姐姐说的对，求图标地址！
> 
> 谢谢！

 图标库用的就是这个：https://www.iconfont.cn/collections/detail?spm=a313x.7781069.1998910419.d9df05512&cid=33

**Comment by iamzaizai** [comment]
@codedart2018 @marren06 @sunyitao     图标库用的就是这个：https://www.iconfont.cn/collections/detail?spm=a313x.7781069.1998910419.d9df05512&cid=33

**Comment by codedart2018** [comment]
> @codedart2018 @marren06 @sunyitao 图标库用的就是这个：https://www.iconfont.cn/collections/detail?spm=a313x.7781069.1998910419.d9df05512&cid=33

你长得真好看，谢谢！

**Comment by sunyitao** [comment]
> @codedart2018 @marren06 @sunyitao 图标库用的就是这个：https://www.iconfont.cn/collections/detail?spm=a313x.7781069.1998910419.d9df05512&cid=33

谢谢🙏
