### ISSUE TITLE
【bug】wx.getSystemInfo 异步导致自定义导航栏可能无法显示

### ISSUE THREAD

**Issue by chatcan** [weilanwl/coloruicss#315]
![image](https://user-images.githubusercontent.com/11750641/92685600-a47d9d00-f36a-11ea-8a14-23ee649cf2f7.png)
此处应该用 wx.getSystemInfoSync 
在微信开发者工具 1.03.2008270 稳定版中出现问题，原因：wx.getSystemInfo 理论上是异步的，可能会出现自定义导航栏无法显示，
望修正 demo。

**Comment by ChowinlI** [comment]
好像用了 wx.getSystemInfoSync后cu-custom组件还是无法拿到globalData的数据呀

**Comment by ProgrammerHuang** [comment]
我也出现类似的情况, 把这段代码移动到了Component内部去了.
#316
