### ISSUE TITLE
为什么要把CustomBar的获取,放在App的onLaunch里呢?

### ISSUE THREAD

**Issue by ProgrammerHuang** [weilanwl/coloruicss#316]
为什么要把CustomBar的获取,放在App的onLaunch里呢?
像下面的Demo代码中的.
![image](https://user-images.githubusercontent.com/9100279/96357237-f1078580-112b-11eb-9fc7-f17b1e8d02e4.png)

不能放在Component的created或ready里面吗?
是有什么原因吗?

放在Component里, 使用不是更方便?

**Comment by ProgrammerHuang** [comment]
下面是改后的Component
增加的ready

`const app = getApp();

Component({
  /**
   * 组件的一些选项
   */
  options: {
    addGlobalClass: true,
    multipleSlots: true
  },
  /**
   * 组件的对外属性
   */
  properties: {
    bgColor: {
      type: String,
      default: ''
    }, 
    isCustom: {
      type: [Boolean, String],
      default: false
    },
    isBack: {
      type: [Boolean, String],
      default: false
    },
    bgImage: {
      type: String,
      default: ''
    },
  },
  /**
   * 组件的初始数据
   */
  data: {
    StatusBar: 0,
    CustomBar: 0,
    Custom: {},
  },
  /**
   * 组件的方法列表
   */
  methods: {
    BackPage() {
      wx.navigateBack({
        delta: 1
      });
    },
    toHome(){
      wx.reLaunch({
        url: '/pages/index/index',
      })
    }
  },
  ready()
  {
    wx.getSystemInfo({
        success: e => {
            const data = {};
            data.StatusBar = e.statusBarHeight;
            let capsule = wx.getMenuButtonBoundingClientRect();
            if (capsule)
            {
                data.Custom = capsule;
                data.CustomBar = capsule.bottom + capsule.top - e.statusBarHeight;
            }
            else
            {
                data.CustomBar = e.statusBarHeight + 50;
            }
             this.setData(data);
        }
    });
  }
})`

**Comment by ProgrammerHuang** [comment]
不要用created, 用ready或attached

**Comment by iamzaizai** [comment]
因为，他只是演示自定义标题栏，毕竟目前colorui不是组件，只是纯css，具体代码，自行调整修改就好了。

**Comment by InsHomePgup** [comment]
所以放在组件里的话，每次调用这个组件都会执行吧？我是放在main js 然后存到缓存里。

**Comment by ProgrammerHuang** [comment]
> 所以放在组件里的话，每次调用这个组件都会执行吧？我是放在main js 然后存到缓存里。

是的,放在ready里,每次组件加载都会执行的.

**Comment by qurge** [comment]
> 因为，他只是演示自定义标题栏，毕竟目前colorui不是组件，只是纯css，具体代码，自行调整修改就好了。

我可以把这段去掉吗？
