### ISSUE TITLE
这个库是不是停止维护了？

### ISSUE THREAD

**Issue by rayyzhong** [weilanwl/coloruicss#323]
最新的发布已经是2019年4月25日的了，目前也积了200个issues

**Comment by zuishuailjc** [comment]
大概是停止维护了，好像也没什么好维护的了？

**Comment by zuishuailjc** [comment]
咕咕咕

**Comment by InsHomePgup** [comment]
> 大概是停止维护了，好像也没什么好维护的了？

哈哈哈哈哈，都在期待3.0的更新。本来是年初就要出来的，结果到现在都还没出。。

**Comment by yawepe** [comment]
还有后续3.0？

**Comment by y0unghe** [comment]
我有个小程序就是用这个，感觉有些bug，希望新版快出来哦。

**Comment by lvcatbo** [comment]
> > 大概是停止维护了，好像也没什么好维护的了？
> 
> 哈哈哈哈哈，都在期待3.0的更新。本来是年初就要出来的，结果到现在都还没出。。

呜呜，现在都2023年了，， 是不是不会再有3.0了
