### ISSUE TITLE
关于字体图标的建议

### ISSUE THREAD

**Issue by jacksonwj** [weilanwl/coloruicss#34]
页面样式做得很棒，但是，给一个小小的建议。

由于 ColorUI 是一个几乎纯 CSS 的库，那么有时为了达到我们自己产品的需求，需要引用其它的库。
大的方向倒是没有什么，只是在字体图标上面：

很多库都用了 `iconfont`，那么，他们的 `font-family` 全部是都是 `iconfont`。

所以，我建议：**将 `font-family` 设置成自己的名称**，比如：

```
// icon.wxss
[class*="icon-"] {
    font-family: "cufont" !important;   // 修改此行
    font-size: ...
    ...
}

@font-face {
    font-family: "cufont";   // 修改此行
    src: ...
    ...
}

// colorui.wxss 中所有用到 iconfont 的地方，比如：
image.loading::after {
    content: "\e7f1";
    font-family: "cufont";   // 修改此行
    position: ...
    ...
}
```

设置成上述名称后，比较能够保证图标的独立性，避免因为 `content` 和别人冲突后，被覆盖的问题。尤其是那些含有 js 组件的类库，几乎都是后加载的，一般都会覆盖 wxss。

**Comment by weilanwl** [comment]
很好的建议，谢谢

**Comment by BenXi630** [comment]
确实有这种情况，建议所有class名前面加上前缀
