### ISSUE TITLE
你他妈不会写就不要写，写得跟他妈一坨屎一样，做你妈呢

### ISSUE THREAD

**Issue by 2962283762** [weilanwl/coloruicss#363]
你他妈不会写就不要写，写得跟他妈一坨屎一样，做你妈呢

**Comment by h7ml** [comment]
> 你他妈不会写就不要写，写得跟他妈一坨屎一样，做你妈呢

玩原神玩的？

**Comment by fish4terrisa-MSDSM** [comment]
> > 你他妈不会写就不要写，写得跟他妈一坨屎一样，做你妈呢
> 
> 玩原神玩的？

我们原神玩家不背这锅 这就只是个垃圾罢了的说
![mmexport51eb53326553dd3c8348fd183f4b9a39_1720153954248](https://github.com/weilanwl/coloruicss/assets/63049888/706c4675-f014-46ca-bbf4-37fccd4af70e)

**Comment by fish4terrisa-MSDSM** [comment]
关issue吧 这个没必要留着的说

**Comment by fish4terrisa-MSDSM** [comment]
> 你他妈不会写就不要写，写得跟他妈一坨屎一样，做你妈呢

所以你项目有star嘛(笑 还是觉得自己做的比这项目更好。。。。。。。?

**Comment by killerddd3** [comment]
别逼逼，拿代码说话。

**Comment by nrvanab** [comment]
你妈没教过你不会说话就闭嘴吗？

**Comment by lanshunfang** [comment]
公众号转了这个：https://mp.weixin.qq.com/s/4vcUMEgnvrJeQY8k64S7tQ
