### ISSUE TITLE
组建需求：浮动按钮

### ISSUE THREAD

**Issue by qingwg** [weilanwl/coloruicss#49]
很漂亮，但是希望有下图类似按钮组件。
![浮动按钮关闭](http://qingwuguo.oss-cn-beijing.aliyuncs.com/other/fabbutton.jpg)
![浮动按钮打开](http://qingwuguo.oss-cn-beijing.aliyuncs.com/other/fabbutton2.jpg)

**Comment by iamzaizai** [comment]
我居然看不见图。。。

**Comment by wojiaoxiaomayun** [comment]
同求呀，这个很重要，来自菜鸟的哭诉
