### ISSUE TITLE
请问是否可以提供ui里图片的psd或ai文件

### ISSUE THREAD

**Issue by chenfeiyu0128** [weilanwl/coloruicss#59]
请问是否可以提供ui里图片的psd或ai文件

**Comment by weilanwl** [comment]
项目相关的资源请关注 语雀的库 https://www.yuque.com/groups/colorui/apply?join_token=7f47940d815b9cf86ced6479cf3a8168 相关UI源文件以后会做 暂时没有

**Comment by youko0** [comment]
请问有最新的地址吗？
