### ISSUE TITLE
mpvue 如何使用

### ISSUE THREAD

**Issue by goldencolor** [weilanwl/coloruicss#61]
是否可以兼容mpvue？
具体如何使用？

**Comment by Zkaim** [comment]
现在应该还不支持~
同意期待中

**Comment by tanyunl** [comment]
在 main.js 
`import Vue from 'vue'
import App from './App'

import '../static/css/app.wxss'
import '../static/css/colorui.wxss'
import '../static/css/icon.wxss'`

就行了。记住不能用 小程序的标签   如 <view class="cu-list menu card-menu margin-top-xl margin-bottom-xl shadow-lg"></view> 改成 
<div class="cu-list menu card-menu margin-top-xl margin-bottom-xl shadow-lg"></div>
支持 <text></text>  
我就试了这么多。。毕况用mp vue 才五分钟 。
第一想法就是看支持这个UI不。

**Comment by xiaomizhou66** [comment]
可以使用么？

**Comment by xiaomizhou66** [comment]
可以使用么？

**Comment by FunnyBoyCN** [comment]
mpVue中如何使用？

**Comment by cgxqd** [comment]
用正则将 mian.css 中的单位替换为 px 即可。
