### ISSUE TITLE
Taro怎么使用呢

### ISSUE THREAD

**Issue by liujians** [weilanwl/coloruicss#63]
9102年了，现在写原生小程序的多吗？考虑一下尽快出编译层面的实现吧

**Comment by ChinaHDJ** [comment]
taro好用吗？我看issue一堆的bug问题。我现在写小程序就是原生的。写的还可以，基本上都是用组件。项目不是很大。但是考虑以后项目大了用框架

**Comment by coppyC** [comment]
多看文档
https://nervjs.github.io/taro/docs/mini-third-party.html

**Comment by coppyC** [comment]
话说，这个好像就是 css 框架吧
代码下下来后
.wxss 改为 .css
然后在 app.css 引入就好了
```css
@import "colorui/main.css";
@import "colorui/icon.css";
```

至于组件引入的方法可以参考文档
https://nervjs.github.io/taro/docs/mini-third-party.html

**Comment by cgxqd** [comment]
用正则将main.css 中的单位替换为Px 即可 。

**Comment by cnscorpions** [comment]
有了这个，还没开始用https://github.com/yinLiangDream/mp-colorui
