### ISSUE TITLE
左右模态框位置滑动

### ISSUE THREAD

**Issue by Akimotorakiyu** [weilanwl/coloruicss#67]
左右模态框位置滑动
![图片](https://user-images.githubusercontent.com/31165554/54673166-aa5b3f00-4b34-11e9-8fac-b5146e87e562.png)

**Comment by weilanwl** [comment]
请使用scrollView包裹，高度用calc计算

**Comment by SilverLeaves** [comment]
这个效果官方示例里的效果。
官方示例里面没有用scrollView包裹。

**Comment by weilanwl** [comment]
好的，了解，这是后面版本改过导航的高度计算，后面修复
